# Generated by Django 4.2 on 2023-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='blog/pdfes'),
        ),
    ]
