# Generated by Django 4.2 on 2023-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blog_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
