# Generated by Django 4.2 on 2023-04-26 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="blog",
        ),
    ]
