# Generated by Django 4.2 on 2023-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="svg_path",
            field=models.CharField(default=1, max_length=450),
            preserve_default=False,
        ),
    ]
