# Generated by Django 4.2 on 2023-04-25 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_service_svg_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="aos_delay",
            field=models.PositiveIntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="icon_box",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="icon_name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
