# Generated by Django 4.2 on 2023-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_service_aos_delay_service_icon_box_service_icon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="svg_path",
            field=models.CharField(max_length=1450),
        ),
    ]
