# Generated by Django 4.2 on 2023-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_service_svg_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birthday", models.DateField()),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("degree", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "My Profile",
            },
        ),
    ]
