# Generated by Django 4.2 on 2023-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_alter_profile_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
