# Generated by Django 4.2 on 2023-04-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0015_project_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_services",
                to="portfolio.profile",
            ),
        ),
    ]
