# Generated by Django 4.2 on 2023-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0019_remove_project_image_alter_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("B", "Backend"),
                    ("M", "Mobile"),
                    ("F", "Frontend"),
                    ("D", "Desktop App"),
                    ("S", "Full Stack"),
                ],
                default=1,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
