# Generated by Django 4.2 on 2023-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0020_project_tech_stack_alter_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="main_image",
            field=models.ImageField(default=1, upload_to="portfolio/images/projects/"),
            preserve_default=False,
        ),
    ]
